name: Build Node.js Runtimes

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"  # Her ayın 1'inde otomatik build
  push:
    branches:
      - main
    paths:
      - nodejs/**
      - .github/workflows/nodejs.yml

jobs:
  build:
    name: "runtimes:nodejs_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 16
          - 17
          - 18
          - 20
          - 21
          - 22
          - 24
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ARM64 desteği için QEMU kurulumu
      - name: Setup QEMU for ARM64 Build
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v7.0.0-28

      # Docker Buildx kurulumu
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      # GitHub Container Registry'a giriş
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Docker image build ve push
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./nodejs
          file: ./nodejs/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/rustopic/runtimes:nodejs_${{ matrix.tag }}
            ghcr.io/rustopic/runtimes:nodejs_${{ matrix.tag }}-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

